# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[git_branch]
format = '路 [$symbol$branch(:$remote_branch)]($style) '

[git_commit]
tag_disabled = false

[golang]
format = '路 [$symbol($version )]($style)'

[package]
format = '路 [$symbol$version]($style) '

[python]
format = '路 [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\)) ]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[container]
disabled = true

[direnv]
disabled = true
